CATALOGUE_HOST: catalogue.rojahanumantharaju.site
USER_HOST: user.rojahanumantharaju.site
CART_HOST: cart.rojahanumantharaju.site
SHIPPING_HOST: shipping.rojahanumantharaju.site
PAYMENT_HOST: payment.rojahanumantharaju.site