- name: copy mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: installing mongodb
  ansible.builtin.dnf:
    name: mongodb-org
    state: present

- name: system start and enabled
  ansible.builtin.service:
    name: mongod
    state: started  #if i write start it will fail reloaded, restarted, started, stopped,
    enabled: yes

- name: edit the configuration File
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: system restart 
  ansible.builtin.service:
    name: mongod
    state: restarted