CART_HOST: cart.backend-{{env}}.rojahanumantharaju.site
USER_HOST: user.backend-{{env}}.rojahanumantharaju.site
RABBITMQ_HOST: rabbitmq.backend-{{env}}.rojahanumantharaju.site
RABBITMQ_USER: roboshop
RABBITMQ_PASSWORD: roboshop123