  - name: creating app directory
    ansible.builtin.file:
     path: /app
     state: directory
  
  - name: creating roboshop system user
    ansible.builtin.user:
     name: roboshop
     system: yes
     home: /app
     shell: /sbin/nologin

  - name: downloading catalogue code
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
     dest: /tmp/catalogue.zip

  - name: extracting or unzipping catalogue code
    ansible.builtin.unarchive:
     src: /tmp/catalogue.zip
     dest: /app
     remote_src: yes
